import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { destinations } from "@/data/destinations";
import { PageCta } from "@/components/ui/page-cta";

export default function DestinationsPage() {
  const [featured, ...supporting] = destinations;
  return (
    <main>
      <section className="bg-[var(--color-charcoal)] text-white"><div className="mx-auto grid max-w-[1400px] gap-10 px-4 pb-20 pt-28 sm:px-6 sm:pb-28 sm:pt-36 lg:grid-cols-[0.8fr_1.2fr] lg:items-end lg:px-8"><div className="max-w-2xl"><div className="mb-5 text-[0.7rem] font-medium uppercase tracking-[0.28em] text-[var(--color-gold)]">Destinations</div><h1 className="font-serif text-[clamp(3rem,8vw,7rem)] leading-[0.86]">Discover Africa at its most elemental.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">From sweeping savannahs to the Indian Ocean, discover places that make every journey through East Africa feel distinctly its own.</p></div><div className="relative min-h-[360px] overflow-hidden rounded-[2rem] sm:min-h-[520px]"><Image src={featured.image} alt={featured.name} fill sizes="(max-width: 1024px) 100vw, 65vw" priority className="object-cover" /><div className="absolute inset-0 bg-black/20" /></div></div></section>
      <section className="bg-[var(--color-ivory)] py-24 sm:py-32"><div className="mx-auto max-w-[1400px] px-4 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><Link href={`/destinations/${featured.slug}`} className="group relative min-h-[520px] overflow-hidden rounded-[2rem] bg-[var(--color-charcoal)] text-white sm:min-h-[640px]"><Image src={featured.image} alt={featured.name} fill sizes="(max-width: 1024px) 100vw, 65vw" className="object-cover transition duration-700 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(15,12,9,0.05),rgba(15,12,9,0.86))]" /><div className="absolute bottom-0 p-7 sm:p-10"><div className="text-[0.68rem] uppercase tracking-[0.22em] text-[var(--color-gold)]">{featured.name} · {featured.region}</div><h2 className="mt-3 font-serif text-6xl leading-none sm:text-8xl">{featured.name}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/75">{featured.summary}</p><span className="mt-6 inline-flex items-center gap-2 text-sm">Explore destination <ArrowRight size={16} /></span></div></Link><div className="divide-y divide-[var(--color-border)] border-y border-[var(--color-border)]">{supporting.map((destination) => <Link key={destination.slug} href={`/destinations/${destination.slug}`} className="group block py-7 first:pt-0 last:pb-0 sm:py-9"><div className="flex items-start justify-between gap-5"><div><div className="text-[0.65rem] uppercase tracking-[0.2em] text-[var(--color-gold)]">{destination.name} · {destination.region}</div><h3 className="mt-2 font-serif text-4xl leading-none text-[var(--color-charcoal)]">{destination.summary}</h3><p className="mt-3 text-sm leading-7 text-[var(--color-muted)]">{destination.highlights.slice(0, 2).join(" · ")}</p></div><ArrowRight className="mt-1 shrink-0 text-[var(--color-gold)] transition-transform group-hover:translate-x-1" /></div></Link>)}</div></div></div></section>
      <PageCta eyebrow="Not sure where to begin?" title="Let&apos;s find the places that fit your journey." description="Tell us what draws you to Africa and we&apos;ll help shape the destinations around your journey." image={featured.image} />
    </main>
  );
}
